### ISSUE TITLE
Do que você precisa? Qual primeiro projeto que você gostaria de desenvolver com a comunidade PHP Brasil do Telegram?

### ISSUE THREAD

**Issue by erikfig** [brasil-php/forum#1]
Vamos iniciar nosso primeiro projeto em comunidade? Faça suas escolhas:

Base de desenvolvimento
- Framework fullstack (Qual?)
- Micro framework (Qual?)
- PHP puro (Daremos suporte a PHP 5.6? ou Apenas o 7?)

Qual projeto?
- Wordpress "do jeito certo" (já rolou algumas discussões sobre esta ideia, rsrs)
- ERP
- Loja Virtual
- Uma rede social (descreva)
- Outro

Meu voto vai para Microframework Slim (já traz o mínimo do mínimo e poderíamos pular isso) e o projeto: ERP.

Manda ai a sua ideia!

**Comment by flavianohonorato** [comment]
Tecnologia: PHP 7 puro, ou um micro fw como Sílex ou Slim.
Projeto: ERP ou Loja virtual.

**Comment by wilcorrea** [comment]
Base de desenvolvimento:
- Micro framework -> Silex (algo com um stack fechado e um guide com as responsabilidades e distribuição das classes no projeto)

Projeto:
- Wordpress "do jeito certo" (um CMS vai ter uma penetração maior na comunidade do que projetos mais robustos para soluções mais completas)

**Comment by marcelorodrigo** [comment]
Acredito que um Wordpress "do jeito certo" será um projeto com roadmap mais razoável e enxuto que uma solução tão grande como um ERP ou uma rede social.

Não vejo como vantagem usar o PHP 7 puro justamente porque várias rodas já estão disponíveis para começar "do jeito certo" :)

**Comment by IgorDePaula** [comment]
Base de desenvolvimento

```
Framework fullstack (Qual?)  Que tal  o expressive?
Micro framework (Qual?)----------^
PHP puro (Daremos suporte a PHP 5.6? ou Apenas o 7?) 5.6
```

Qual projeto?
    Outro -> sistema de provas dinamico (pra iniciar)

**Comment by FredericoSFerreira** [comment]
Base de desenvolvimento
    Framework fullstack:  Laravel
Projeto
     Loja Virtual

**Comment by vinicius73** [comment]
Base de desenvolvimento
Framework fullstack: Laravel
Projeto
API Restful para forum

Se esse proposta passar colocarei em palta com a comunidade VueJS para criar o front-end em VueJS
Sendo uma API Restful qualquer um pode criar um cliente para o forum.

**Comment by mauriciord** [comment]
Micro framework Slim ou Php puro 7
Projeto ERP

**Comment by prhost** [comment]
**Base de desenvolvimento:**
Webapp = Laravel + Vuejs

**Projeto:**
https://github.com/git-to-book/example-book/blob/master/README.md

**Comment by raisiqueira** [comment]
Micro framework, e um ERP seria bacana. Mas Acho q vai surgir um problema do micro quando o projeto ficar grande demais, caso isso ocorra, deve-se haver um estudo antes de iniciar o projeto e qual banco vai ser usado.

**Comment by felipemarques8** [comment]
Base de desenvolvimento
Framework fullstack: Laravel
Projeto
Erp

**Comment by Lucasktrindade** [comment]
Base de desenvolvimento: Laravel.Podendo ser uma API pois assim.conseguimos criar um APP para consumir.
Projeto: Criação de um CMS para educação, parecido com o moodle.

**Comment by erickosma** [comment]
Base de desenvolvimento
Framework fullstack: Laravel
Projeto
ERP ou Criação de um CMS

**Comment by raisiqueira** [comment]
@Lucasktrindade a ideia de um CMS para educação é uma boa!

**Comment by igor822** [comment]
Framework Fullstack: Symfony
Projeto: ERP

@raisiqueira concordo, se for um Micro framework para um projeto grande como um ERP, pode dar vários problemas com relação à manutenção com o tempo, a não ser que seja definido um padrão de desenvolvimento, como qual a arquitetura (MVC, ADR), quais pacotes utilizar para roteamento, banco de dados, entre outros.

**Comment by WendellAdriel** [comment]
**Base de desenvolvimento:** `Framework FullStack Laravel` ou `Microframework Lumen` para criação da `API` e `Vue.js` para criação do Front-end;
**Projeto:** Um `LMS` Restful;

**Comment by drpacheco** [comment]
Projeto: ERP Voltado a empresas de contabilidade para auxiliar clientes que ainda usam sistema Emissor de NFe Gratuito.

**Comment by lucascdsilva** [comment]
Base de desenvolvimento
Micro framework: [Silex ou Expressive]
Projeto: sugestão @drpacheco (ERP Emissor NFe Gratuito) ou sugestão do @IgorDePaula  (sistema de provas dinâmico) , mas acho que é bom realizamos um pré-projeto pra analisamos como vamos nos sair e ajustar um cronograma.

Minha stack hoje é : Doctrine + symfony/http-foundation + lcobucci/jwt + ( meu Router 😄  )

**Comment by flavio-silva** [comment]
Base de desenvolvimento: Laravel
Projeto: Gerenciador de projetos

Acho que se utilizarmos um full stack não nos preocuparemos se o projeto crescer muito.

Faria uma API com Laravel e no front pode ser o Vue.js

**Comment by phalmeida** [comment]
Framework: Laravel
Projeto: ERP

**Comment by elton182** [comment]
Framework: slim
Projeto: ERP

**Comment by raisiqueira** [comment]
O projeto ideal que vai solucionar o problema de várias pessoas, seria um emissor de NFe. Daí o cenário ideal para mim seria Laravel como framework.

**Comment by rubenszuliani** [comment]
Projeto Bom seria um sistema de Helpdesk, web, com um sistema mobile, onde o cliente poderia checar seus tickets
Cakephp 3, com angularjs 2, ionic 2, server rast, ACL 
=D

**Comment by maiconpinto** [comment]
Eu gostei de várias ideias aqui, eu apoio muito qualquer um com CakePHP. 
Sugestão: Emissor de NFe Gratuito

**Comment by allantorres** [comment]
Que tal desenvolver algo social? Que sirva para o Brasil de alguma forma? 
Ei acredito que temos que usar essa mágica que temos nas mãos chamada programação para o bem do próximo! Podemos ajudar o Brasil a mudar alguma coisa... que tal?

**Comment by celsodavid** [comment]
Framework: Slim
Projeto: ERP, Loja Virtual ou um Sistema de ensino online

**Comment by fagnersilva** [comment]
Framework: Laravel
Projeto: ERP

**Comment by fagnersilva** [comment]
Framework: Laravel
Projeto: Plataforma de Telefonia IP (Monitoramento de ambientes, Administração de cadastros, Relatórios de chamadas e estatísticas, Gravação de chamadas, URA de atendimento automático, Ramais IP’s ilimitados, Conferência e correio de voz e Tarifador).

Se essa proposta passar colocarei em pauta com a Fundação Asterisk Libre para criarmos o PBX.

**Comment by robmachado** [comment]
ERP é uma necessidade e um desejo muito grande de toda a comunidade PHP.
Mas para uma coisa tão complexa somente com um Framework (fullstack) : LARAVEL (sem duvida nenhuma).

**Mas um emissor de NFe também pode ser uma boa ideia, isso foi iniciado no nfephp-org mas ainda está engatinhando. Nesse caso seria um backend com LARAVEL (em restful) e um frontend em AngularJS (com a possibilidade de uso do ElectronJS).**

**Comment by erandirjunior** [comment]
Gostei de todas as ideias, sendo desenvolvido em laravel ou php puro, apóio totalmente.

**Comment by robmachado** [comment]
Eu acrescentaria mais informações sobre a estrutura de um projeto (qualquer que ele seja):
- LARAVEL (fullstack)
- Restful (para poder usar com múltiplas formas de acesso)
- OAuth2 na autenticação (para melhoria da segurança de acesso)
- PHP 7

**Comment by helam01** [comment]
Algum Micro Framework ou PHP 7 puro com design patterns, com algum framework JS, Angular ou Meteor.  

Projeto: CMS ou algum projeto do tipo automação de email marketing.

**Comment by mbrunogregorio** [comment]
Framework: Slim(Pela imparcialidade, Cakers puxando a sardinha pro cake e laravelers puxando sardinha pra Laravel)
Projeto: NFE
Php 5.6

**Comment by micdoug** [comment]
Estou vindo da plataforma dotnet (ASP.NET MVC e Web API) e python (Django) então não conheço frameworks PHP direito.

Quanto ao projeto uma coisa bacana seria uma ferramenta web voltada para desenvolvedores free-lancers controlarem os projetos que estão trabalhando. Teria o cadastro dos projetos, um checklist de funcionalidades acordadas com os clientes, cadastro de prazos, cadastro de interações com os clientes. No caso em que é feita cobrança mensal poderia ter algum tipo de controle de recebimento, mesmo que tenha que ser feito de forma manual. Notificação de renovação de domínio, etc ....
