### ISSUE TITLE
Votação de projeto

### ISSUE THREAD

**Issue by erikfig** [brasil-php/forum#2]
Depois do Hangout de ontem (com muitas dicas legais e até algumas tretas leves, rsrs) decidimos por 2 projetos e mais 1 que eu vou adicionar.
1. API RESTful para Q/A nos padões StackOverflow (aplicação estilo cliente/servidor) - Ainda vamos votar e discutir as ferramentas e tecnologias a se usar.
2. NFe (em PHP puro, digo, qualquer relação com frameworks será desenvolvida depois) - Para este vamos precisar de alguém "da área" para nos auxiliar
3. Plataforma de ensino RESTful

Outra sugestão é o ERP, que embora seja complexo de mais, pode ser quebrado em partes menores para ser trabalhado, como um CRM ou Sistema Financeiro... ou seja, por módulos, mas ainda assim vou abrir outra issue sobre o assunto, por favor, não comentem sobre isso nesta issue!!!!

Desculpem, preferi um número impar de sugestões, não sou muito fan de números pares (e sim, é preconceito com números pares, me processem).

ATENÇÃO! VOTOS DUPLICADOS SERÃO DESCONSIDERADOS!

**Comment by wilcorrea** [comment]
Voto no 1

**Comment by marcelorodrigo** [comment]
1

**Comment by vinicius73** [comment]
Deem :+1: aqui para Opção 1

**Comment by vinicius73** [comment]
Deem :+1:  aqui para Opção 2

**Comment by vinicius73** [comment]
Deem :+1: aqui para Opção 3

**Comment by fsoaresjunior** [comment]
2

**Comment by vinicius73** [comment]
@wilcorrea, @marcelorodrigo e @fsoaresjunior  
Para não tumultuar vou excluir seus comentários, por favor marquem as opções de vcs :) 
Outros tipos de comentários são bem vindos

**Comment by ravanscafi** [comment]
Olá! Caí de paraquedas por aqui, aí acabei perguntando pro @vinicius73 qual seria o objetivo do brasil-php de desenvolver algo. Ele me disse que seria mais ou menos no sentido de reunir a comunidade e também aprender.

Pensando nisso, eu, que já trabalhei com NF-e uns anos atrás, gostaria de expressar **minha opinião**:
NF-e não é nada fácil de fazer, nem manter. Precisa ter um background bom na área. Sempre está mudando e tal, novas normas precisam ser aplicadas com prazos limite e etc. Tem várias empresas que fazem somente isso, justamente pela dificuldade. O desafio maior não vai ser a linguagem, nem a implementação, mas sim entender as regras da NF-e. Além disso, é um conhecimento que não se aplica muito pra outras áreas, é muito específico. O processo de code-review vai ser custoso por ter que validar as regras e etc.

Então, embora pareça uma ideia promissora do ponto de vista da necessidade de mercado, não é a toa, é porque não é simples mesmo de se manter algo assim. Talvez as outras ideias se encaixem melhor pra atingir o objetivo que vocês tão procurando.

**Comment by walkeralencar** [comment]
@rscafi complementando essa informação, o projeto NFePHP (https://github.com/nfephp-org/sped-nfe), está disponível para colaboração, estão passando por um refactoring para criar versão compatível com PSRs e PHP Puro, sem dependência de framework, ou seja, esse projeto já existe e pode crescer com devida colaboração da comunidade.

A primeira versão do projeto foi desenvolvida em 2008/2009 (https://github.com/nfephp-org/nfephp) e naquela época não havia as PSRs para serem seguidas. Depois disso surgiu o Sped, juntando as duas coisas foi decidido um refactoring geral no projeto.

No mais, faço da suas palavras as minhas.

**Comment by wmbonfiglio** [comment]
Eu acho que a parte de Forum é algo um pouco batido, com várias implementações já feitas. Também é um pouco superficial, acaba não entrando em muitos detalhes técnicos que aplicações completas enfrentam normalmente.

Eu tenho um sistema de ensino em Laravel e posso dizer que é um desafio bem interessante, envolve muitas questões que a princípio parecem simples mas vão se mostrando um pouco mais complexas (o que é ótimo para o aprendizado). Toda a parte de inscrição, controle de acesso/vencimento, admin com geração de relatórios, módulo de gamification.... Daria pra começar com o básico e deixar aberto para "módulos", o que tornaria o projeto infinito :mortar_board:

**Comment by vinicius73** [comment]
Sobre o forum, uma das ideias é justamente começar com algo simples e que outras comunidades possam participar. 

Uma vez que os endpoints sejam definidos o client pode ser feito em VueJS ou ReactJS 

Também é possível haver mais de uma implementação do fórum, quem sabe zend, Laravel, Cake e symfony... Uma comparação real de projetos reais. Até mesmo outras linguagens. 

E mesmo que seja algo simples, nada impede de possuir features complexas como ranking de membros, pontuação, melhor resposta... Algo nos moldes do Stackoverflow

**Comment by hibviny** [comment]
@rscafi concordo contigo! Mexo com isso todo dia e é uma zona! Sai nota técnica toda hora com prazos absurdos e ninguem sabe explicar direito como funciona as paradas. Creio que o projeto do forum ou da plataforma de ensino seja mais interessante para reunir a comunidade e disseminar as boas práticas do PHP.

**Comment by erikfig** [comment]
Vejo uma inesperada reviravolta no horizonte....

**Comment by elton182** [comment]
na minha opinião a plataforma de ensino seria um projeto muito melhor pois existem vários desafios como:
- streaming de vídeo aulas 
- frontend web, mobile e desktop
- controle de alunos, com notas 
- gamification com level e experiência dos alunos
- emissão de certificados
- controle financeiro
- loja de cursos com checkout e pagamentos com cartão

e muito mais ...

**Comment by erikfig** [comment]
Eu iria curtir também uma plataforma EAD

**Comment by vinicius73** [comment]
Por outro lado pensem em criar um ambiente stackoverflow open-source.
- ranking de usuários baseado em pontos 
- melhores respostas 
- categorização e buscas avançadas 
- moderadores 
- blogs 

Uma plataforma de ensino tem um público mais fechado, enquanto uma plataforma estilo stackoverflow teria mais aberturas. 
Depois pode-se até pensar em ampliar a plataforma para um sistema de vídeo-aulas gratuitos.

**Comment by erikfig** [comment]
Que revira volta... nfe caindo...

**Comment by shutdown90** [comment]
Opção 3.

**Comment by tchicotti** [comment]
Opção 3

**Comment by vinicius73** [comment]
@shutdown90 e @tchicotti 
Estou apagando seus comentário para não tumultuar, por favor manquem :+1: nas opções que vcs desejam.

**Comment by danilomartins90** [comment]
Opa, desculpa ai, eu tinha entrado pelo celular e por lá não apareceu o botão votar.

**Comment by Lucasktrindade** [comment]
Acho uma plataforma de ensino algo bem grande porém necessário, e um fórum faz parte de uma plataforma de ensino. Penso que poderíamos começar com o fórum e a partir dele ir criando novas features para chegar em uma plataforma de ensino.

**Comment by madprolondon** [comment]
Opção 3 por ter mais maneiras de agregar os conhecimentos
